### ISSUE TITLE
Image detection & compression.

### ISSUE THREAD

**Issue by BonnieDoug** [WeAreAthlon/frontend-webpack-boilerplate#1]
Hi, I'm currently trying to replace my companies massively outdated and super slow Gulp + Bower setup with this Webpack implementation. Everything is working great with only a couple of tweaks, except for images.

I have all my raw images in the `./src/images/` folder yet when I run `npm run build` the images are not being compressed and copied to `./dist/images` how can I resolve this? I've got the feeling it's searching my app for used images, but as this is website is primarily php based the actual html/php files don't exist and don't get checked over by the webpack setup at all. Which I'm fine with, I simply want it to process and dump the entire images folder if possible.

On a side note, thank you for this great boilerplate, it has saved me a huge amount of time already.

**Comment by chemicalbr** [comment]
Hi, I've added a PR addressing your issue with inline (in html) images and their compression.
You can check it out in this branch 
https://github.com/WeAreAthlon/frontend-webpack-boilerplate/tree/issue/1-inline-images-and-compression

**Comment by pnikolov** [comment]
Images are now separated into two directories `src/images/design/` and `src/images/content/`

I've limited the image copy functionality to only scope the _content_ images, as initially the [`copy-webpack-plugin`](https://github.com/webpack-contrib/copy-webpack-plugin) was copying all the source files too. 

All images placed into `src/images/content` will be copied into `dist/images/content` on build.

**Comment by pnikolov** [comment]
This feature is part of [Release v2.4.0](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v2.4.0)
