### ISSUE TITLE
Development server add or a better guide for beginners how to implement it

### ISSUE THREAD

**Issue by ivan-vilches** [WeAreAthlon/frontend-webpack-boilerplate#12]
* **What is the expected behavior?**
running : npm run watch,  will be nice open the browser syncronized with the dev .

* **What is the motivation / use case for changing the behavior?**
Quick start to develop, are many people getting away from webpack beacouse beginners like me is hard to grasp. 
running:  npm run watch open localhost dist on port 3000 but not load anything, not sure how works with the package.
Thanks

* **Please tell us about your environment:**
  
  - Version: 10
  - System / Windows ]
  - Language: [all | SASS | ES6/7 | ES5 ]

* **Other information** (_e.g. detailed explanation, stack-traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc_)
sasasasasasassa

**Comment by pnikolov** [comment]
@ivan-vilches 

As it is stated in the [README](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/blob/master/README.md) the current version of this boilerplate does not include development server. There is a configuration setting in the [webpack.config.js](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/blob/3b061d716303046356278806c7a6234dcd7fdb7c/webpack.config.js#L5)  to specify your local development server. 
So to fix your issue you need just to specify the correct path to **your local dev web server**  and more specifically to your project path - *e.g `http://localhost:port/path/to/project/`* in the `webpack.config.js`

It would be good to share what would be useful for beginners - wiki pages, examples, sample project?

*P.S I am planning to release a new major version with included development web server setup and configuration aligned with the watcher. This would introduce a new set of dependencies but it would be useful for beginners.
