### ISSUE TITLE
SCSS Sourcemaps 

### ISSUE THREAD

**Issue by mantsch** [WeAreAthlon/frontend-webpack-boilerplate#17]
Hey, thanks for your boilerplate, i currently use it in a project, but was missing the scss sourcemaps. 
I added them temporarily to my project with the following options, but this could probably be improved.

```
    devtool: 'source-map',
    module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            'style-loader', 
            MiniCssExtractPlugin.loader, 
            'css-loader',
            { loader: 'postcss-loader', options: { sourceMap: true } },
            { loader: 'sass-loader', options: { sourceMap: true } }
          ],
        },
```

**Comment by GorillazJS** [comment]
Another good idea would be to remove lint-sass and add stylelint.
stylelint.io
https://github.com/bjankord/stylelint-config-sass-guidelines

**Comment by pnikolov** [comment]
@GorillazJS it seems that https://stylelint.io is getting more popular than `sass-lint`. Here is a brief comparison - https://stackshare.io/stackups/sass-lint-vs-stylelint

So I think we can consider switching to `stylelint` but it will require configuration change that will take time. Thanks for sharing.

**Comment by pnikolov** [comment]
@mantsch 

In the latest release [`v5.0.0 - Webpack 5 Support`](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v5.0.0) we have added support for easy configuration of the `sourcemaps` strategies for development/production environment. 

If you want source maps consider reading this [Devtool Qualities](https://webpack.js.org/configuration/devtool/#qualities). It explain the different types and what they are best suited for.

You can define a `sourcemap` strategy under:
* [`configuration/webpack.dev.config.js`](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/blob/master/configuration/webpack.dev.config.js#L11)
  * Specify `devtool` value. For the possible values see [`devtool for development`](https://webpack.js.org/configuration/devtool/#development) reference.
* [`configuration/webpack.prod.config.js`](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/blob/master/configuration/webpack.prod.config.js#L12) 
  * Specify `devtool` value. For the possible values see [`devtool for production`](https://webpack.js.org/configuration/devtool/#production) reference. 
    * You should configure your server to disallow access to the Source Map file for normal users!

**Comment by mantsch** [comment]
What an awesome update, thank you so much!
