### ISSUE TITLE
Documentation is not up to date or webpack config is wrong

### ISSUE THREAD

**Issue by devshack** [WeAreAthlon/frontend-webpack-boilerplate#188]
**Describe the bug**

Documentation is not up to date or webpack config is wrong.

**To Reproduce**

In the docs, it's stated that after a production build the fonts will be in an own directory:

> Fonts are located under /dist/fonts/

That's not correct. The current webpack config will move the fonts into /dist/images/fonts/ - which is odd anyway.

Also, turning on hashing in the webpack config doesn't include the .css and .js file per default.

**Expected behavior**

Fonts are moved to /dist/fonts/ according to the documentation.

**Comment by pnikolov** [comment]
@devshack the reported behaviour of the fonts directory path location was fixed in the latest release [v5.17.0](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v5.17.0).
> Bugfix: Update webpack configuration to build font files in dedicated fonts directory.

Are you still experiencing this issue after updating to the latest version of the configuration?

**Comment by devshack** [comment]
@pnikolov Well, I've downloaded the latest release (.zip) today (not the git repo itself), so I suppose I had the latest version 😅

**Comment by pnikolov** [comment]
@devshack you are right, I've not fully fixed this.

I've just committed a fix in the `master` branch, you can get it from there, this fix will be part of the next release, too.

https://github.com/WeAreAthlon/frontend-webpack-boilerplate/blob/7887e9cf95f691b5e02dd0f0924177d3c702f6f4/webpack.config.js#L68-L70

**Comment by pnikolov** [comment]
@devshack is the latest code from `master` working for you, can I close this issue?

**Comment by devshack** [comment]
@pnikolov Looks good ;)

**Comment by pnikolov** [comment]
OK I am closing this then, and will refer it in the release notes for the next release.
