### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by dangelion** [WeAreAthlon/frontend-webpack-boilerplate#19]
Hi
have you ever considered of add a cache busting system.
I know it's possible because I use [Sage 9](https://github.com/roots/sage/blob/9.0.9/resources/assets/build/webpack.config.js) that implements it and it works very very well.
Basically when launching `npm run production` it adds an hash code at the end of `app.css` and `app.js` (like `app-hd6sgd4.css`)
What do you think about?

**Comment by pnikolov** [comment]
Hi @dangelion,

Adding hash code to the build JS/CSS file names can be achieved with additional `webpack` configuration but I think this would break the integration of an external application that uses these files. After each assets building you need to change the referenced filenames in the external application.

Speaking about WordPress, WordPress has its own way of cache invalidation - (_both [`wp_register_script`](https://developer.wordpress.org/reference/functions/wp_register_script/) and [`wp_register_style`](https://developer.wordpress.org/reference/functions/wp_register_style/) has parameters to specify the version for cache invalidation_).

Anyhow, adding hashes to the output files can be achieved by amending the current `webpack.config.js`:

```js
output: {
  filename: 'js/[name].[hash:6].js',
  path: path.resolve(__dirname, 'dist'),
},
...
plugins: [
  new MiniCssExtractPlugin({
    filename: 'css/[name].[hash:6].css',
  }),
]
```
Now, after building you would have the following:

```
dist/
  js/app.5db116.js
  css/app.5db116.css
```

**Comment by dangelion** [comment]
Thanks @pnikolov for your solution. That's ok but as you said you'll need to manually update in the code the new name of compiled assets everytime. The mentioned Sage 9 (starter theme for WP) automatically does it. You know how could implement that or a similar in your boilerplate?

**Comment by pnikolov** [comment]
@dangelion 
This cannot be done is this template as it is not theoretically possible - it does not know what external application will load the built assets - that is why the build assets should be following consistent naming - e.g without the hash part.

Such integration should be done from the external application side - e.g configure WordPress to scan the `/dist` directory and load all `.js` and `.css` files there - in this case you can have both the hashes and WordPress loading them automatically after each build process.
