### ISSUE TITLE
Live reload 

### ISSUE THREAD

**Issue by mmajk55** [WeAreAthlon/frontend-webpack-boilerplate#20]
Hi, 

I have a problem with live reload. I'm starting a project with `npm run dev` command and on every change page is reloading, but changes are not applied. Only hard reload helps

**Comment by pnikolov** [comment]
Hi @mmajk55, 

Can you specify your development environment setup or more easily just follow the [bug issue template](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/issues/new?template=bug.md)?

Also can you describe which changes does not apply with the live reload? (HTML/CSS/SASS/JS?)
