### ISSUE TITLE
Lint of styles (SASS) doesn't work

### ISSUE THREAD

**Issue by vadymstebakov** [WeAreAthlon/frontend-webpack-boilerplate#22]
Hi, I found mistake in package's scripts: `"lint:sass": "sass-lint 'src/scss/*' -v -q"`.
You should rewrite to `"lint:sass": "sass-lint src/scss/* -v -q"`, without quotes for path to styles files.
After that it will work. Incomprehensible, but in the documentation for [sass-lint](https://www.npmjs.com/package/sass-lint#cli-examples) wrote like in your package.json and it doesn't work!

**Comment by pnikolov** [comment]
@vadymstebakov 

Can you specify your development environment setup or more easily just follow the [bug issue template](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/issues/new?template=bug.md)?

In the [documentation](https://github.com/sasstools/sass-lint/blob/develop/README.md#specify-a-config) of `sass-lint` is clearly stated that the quotes should be used when using glob patterns:

> Please note that when using glob patterns such as folder/**/*.scss as a command line argument (files to be linted or ignored) you will need to wrap the pattern in quotes or escape the * characters **to prevent bash/zsh from automatically expanding the glob** pattern.

So following the instructions the quotes are **needed to make sure the pattern is not automatically expanded** from your terminal?

I cannot reproduce your issue, can you elaborate more?

**Comment by vadymstebakov** [comment]
@pnikolov

I used your boilerplate without changes. My environment it's Windows.
I tried to use your boilerplate on the Linux and it was work with quotes, but on the Windows it wasn't work.

**Comment by pnikolov** [comment]
I've researched for a similar problem on Windows and it turns out that there are such issues reported. People have managed to fix it by moving the path from npm script into `.sasslintrc` file (_uncomment the "include" option_):

`package.json`
```json
"lint:sass": "sass-lint -v -q"
```

`.sasslintrc`
```yml
files:
    include: 'src/scss/*'
```

Try this and if it works, we can consider moving the path part as part of the `.sasslintrc` file as change in the next release to be cross platform compatible.

**Comment by vadymstebakov** [comment]
Yes, you are right!
It's work for Windows.
Thx.

**Comment by vadymstebakov** [comment]
@pnikolov 

Hello.
One more thing. Can you remove quotes from `.sasslintrc`
`
files:
    include: src/scss/*
`

SassLint extention of VSCode doesn't work due to those reason.
