### ISSUE TITLE
Run 'CleanWebpackPlugin' before all PostCSS plugins

### ISSUE THREAD

**Issue by Jugibur** [WeAreAthlon/frontend-webpack-boilerplate#23]
I want to use the PostCSS plugin  ['postcss-extract-media-query'](https://github.com/SassNinja/postcss-extract-media-query) and it runs correctly.
The problem is, that this plugin runs **before** 'CleanWebpackPlugin' is executed and so all files will be removed instantly.

I've extended the webpack.config.js with the following:
`{
      loader: 'postcss-loader',
      options: {
        postcssOptions: {
          plugins: (loader) => [
            require('postcss-extract-media-query')()
          ]
        }
      },
  },`
and of course I have extended the postcss.config.js file.

I've read and tried a lot but I must admit this Webpack config things are still a mystery for me, so if you could point me to the right direction, this would be great.

**Comment by pnikolov** [comment]
@Jugibur 

I've managed to reproduce your issue and have tried with different options of the `CleanWebpackPlugin` but without any success. I think something is wrong with [`SassNinja/postcss-extract-media-query`](https://github.com/SassNinja/postcss-extract-media-query) in terms of how the plugin registers its output files and the way webpack 5 is working. 

I've tried using the suggested webpack loader and plugin [`SassNinja/media-query-plugin`](https://github.com/SassNinja/media-query-plugin) - as stated from the author it is specifically targeted to `wepback`. Unfortunately the latest version of `media-query-plugin` does not support `webpack` 5 - [Error with webpack 5](https://github.com/SassNinja/media-query-plugin/issues/54) so I've no solution for this case yet.

**Comment by pnikolov** [comment]
@Jugibur I can share and idea for a workaround:
* Configure the output of the `postcss-extract-media-query` to be **outside** of the `dist` directory and then modify the build command to move the files in the dist at the end, e.g if you have configured the output to be in the root of the project:

```shell
npm run build && mv app-*.css /dist/css
```

**Comment by Jugibur** [comment]
First thanks for your effort and your notes due to incompatibilities with Webpack 5! 
I have now found another plugin for extracting media queries ([https://github.com/elambro/extract-css-media-queries](extract-css-media-queries)), which offers more useful options for me.
There are problems there too, but they seem to be (also) related to the plugin. Let's see if I can make it work....
