### ISSUE TITLE
mp4 video is not viewing

### ISSUE THREAD

**Issue by tiggem1993** [WeAreAthlon/frontend-webpack-boilerplate#25]
I have put one mp4 video in my images folder, and trying to call in html, I also install the file-loader added in webpack.config.js file as per documentation.

**index.html**
`<video autoplay muted loop id="myVideo">   
        <source src="../images/design/rain.mp4" type="video/mp4">
      Your browser does not support HTML5 video.
    </video>`

webpack.config.js
`{
        test: /\.(mp4)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'images/design/[name].[ext]',
              publicPath: '../',
            },
          },
        ],
      },`

But video is not viewing. Also inspect the path in browser which is showing correct as expected.
`http://localhost:8000/images/design/rain.mp4`

Please help me how to fix this issue?

**Comment by tiggem1993** [comment]
Hi @pnikolov , I have also taken this article reference but didn't get any success. https://medium.com/@accardo.steven/a-solid-webpack-config-and-the-knowledge-behind-it-78be39f5700d

**Comment by pnikolov** [comment]
Hi @tiggem1993 

The simplest way of loading the video is directly placing in into the `src/images/content/` directory as it gets copied from the `CopyWebpackPlugin` - it will be copied to the `dist/images/content` and in the template you can reference it with the:
```html
<video autoplay muted loop id="myVideo">
  <source src="images/content/rain.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>
```
You can configure the `CopyWepbackPlugin` to work with dedicated `src/videos` directory if needed.

Regarding the `file-loader` you can try it with combination of `html-loader` to enable the `source src` attribute. Here is a topic - [Load video mp4 webpack loader](https://stackoverflow.com/questions/49943372/load-video-mp4-webpack-loader)

**Comment by tiggem1993** [comment]
> Hi @tiggem1993
> 
> The simplest way of loading the video is directly placing in into the `src/images/content/` directory as it gets copied from the `CopyWebpackPlugin` - it will be copied to the `dist/images/content` and in the template you can reference it with the:
> 
> ```
> <video autoplay muted loop id="myVideo">
>   <source src="images/content/rain.mp4" type="video/mp4">
>   Your browser does not support HTML5 video.
> </video>
> ```
> 
> You can configure the `CopyWepbackPlugin` to work with dedicated `src/videos` directory if needed.
> 
> Regarding the `file-loader` you can try it with combination of `html-loader` to enable the `source src` attribute. Here is a topic - [Load video mp4 webpack loader](https://stackoverflow.com/questions/49943372/load-video-mp4-webpack-loader)

Thanks @pnikolov , It works. I just place my video in `src/images/content/` directory and video is surprisingly viewing.
