### ISSUE TITLE
Extra libraries

### ISSUE THREAD

**Issue by theaminuldev** [WeAreAthlon/frontend-webpack-boilerplate#252]
Extra libraries like [jquery](https://jquery.com/), [swiperjs](https://swiperjs.com/), [wowjs]( https://wowjs.uk/) and [animate]( https://animate.style/ ) etc. There may be many more libraries in which file should I put them?

**Comment by pnikolov** [comment]
@theaminuldev each extra library you want to add should have plugin provider / loader and specific documentation on how to use it with web pack. There are multiple use-cases - e.g external jQuery, or installed via `npm`, etc.

Here is for jQuery:
* https://stackoverflow.com/a/63648370/1800369
