### ISSUE TITLE
(node:13772) [DEP0148] DeprecationWarning

### ISSUE THREAD

**Issue by mityaua** [WeAreAthlon/frontend-webpack-boilerplate#26]
**Is your support request related to a problem? Please describe.**

After clean install, I see next message:

(node:13772) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\mitya\Desktop\testfolder\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

My steps:
git clone;
delete .git folder
npm ci;
npm run dev;

How do I fix it?

**Describe alternatives you've considered**

I've tried re-installing uninstall several times.

**Additional context**

Node version: v15.5.1
NPM version: 7.3.0

Full log:

PS C:\Users\mitya\Desktop\testfolder> npm run dev

> @weareathlon/frontend-webpack-boilerplate@5.3.0 dev
> webpack serve --config configuration/webpack.dev.config.js --mode=development

i ｢wds｣: Project is running at http://localhost:8000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from C:\Users\mitya\Desktop\testfolder\dist
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /
(node:13772) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Users\mitya\Desktop\testfolder\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
i ｢wdm｣: assets by info 860 KiB [immutable]
  asset fonts/DINPro-Regular.acf8fe.svg 412 KiB [emitted] [immutable] [from: src/fonts/DINPro-Regular.svg] (auxiliary name: app)
  asset fonts/DINPro-Regular.2ac4eb.eot 178 KiB [emitted] [immutable] [from: src/fonts/DINPro-Regular.eot] (auxiliary name: app)
  asset fonts/DINPro-Regular.f8ce19.ttf 177 KiB [emitted] [immutable] [from: src/fonts/DINPro-Regular.ttf] (auxiliary name: app)
  asset fonts/DINPro-Regular.7b307e.woff 77.6 KiB [emitted] [immutable] [from: src/fonts/DINPro-Regular.woff] (auxiliary name: app)
  asset images/design/heading.499bf3.png 15.9 KiB [emitted] [immutable] [from: src/images/design/heading.png] (auxiliaryassets by path images/content/ 240 KiB
  asset images/content/header.png 238 KiB [emitted] [from: src/images/content/header.png] [copied]
  asset images/content/github.png 1.49 KiB [emitted] [from: src/images/content/github.png] [copied]
  asset images/content/logoa.svg 651 bytes [emitted] [from: src/images/content/logoa.svg] [copied]
assets by chunk 916 KiB (name: app)
  asset js/app.js 909 KiB [emitted] (name: app)
  asset css/app.css 6.26 KiB [emitted] (name: app)
asset index.html 21.9 KiB [emitted]
asset favicon.ico 1.12 KiB [emitted]
Entrypoint app 916 KiB (860 KiB) = css/app.css 6.26 KiB js/app.js 909 KiB 5 auxiliary assets
runtime modules 1.25 KiB 6 modules
modules by path ./node_modules/ 335 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/webpack/hot/ 1.58 KiB 3 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
modules by path ./src/ 340 bytes (javascript) 6.26 KiB (css/mini-extract)
  modules by path ./src/js/*.js 290 bytes
    ./src/js/app.js 91 bytes [built] [code generated]
    ./src/js/demo.js 199 bytes [built] [code generated]
  modules by path ./src/scss/*.scss 50 bytes (javascript) 6.26 KiB (css/mini-extract)
    ./src/scss/app.scss 50 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/scss/app.scss 6.26 KiB [code generated]
webpack 5.22.0 compiled successfully in 19899 ms
i ｢wdm｣: Compiled successfully.

**Comment by pnikolov** [comment]
Hi @mityaua 

This deprecation warning will not prevent the template from proper building your assets.
As far as I can see the warning is generated from the [`postcss`](https://www.npmjs.com/package/postcss) here is the issue discussing this warning with different versions of node [DeprecationWarning: Use of deprecated folder mapping](https://github.com/postcss/postcss/issues/1455).

**Comment by mityaua** [comment]
Yes, indeed, your "plate" works without errors, only this notification.

Does this mean that the next warning has nothing to do with this? Or am I doing something wrong with the pictures?

I just put image in the src/images folder and then npm run production (or npm run build). Compression not working? File size has not changed.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (500 KiB).
This can impact web performance.
Assets:
  images/content/everest_mountain.jpg (3.03 MiB)

WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.22.0 compiled with 2 warnings in 22824 ms

<header>
      <img src="../images/content/everest_mountain.jpg" alt=""> ...

**Comment by pnikolov** [comment]
@mityaua 

Images part of the content  (_`<img>` tags and files placed under `src/images/content`_) are not part of the design of the page and does not go through optimisation as the assumption here is that they have been uploaded via CMS or something similar, like they are dynamic generated images - published in "runtime" etc.

All images part of the design itself (CSS backgrounds, etc.) are being optimised during the "build" assets process.

This is the default behaviour, you can change directory names or reconfigure if you want to optimise the content images if you build a fully static templates that are not targeted to be embedded in a server side web application.
