### ISSUE TITLE
How to use src/templates?

### ISSUE THREAD

**Issue by intellent** [WeAreAthlon/frontend-webpack-boilerplate#31]
In your docs it says:

> HTML files are located under src/templates/
> 
> It will automatically build all HTML files placed under src/templates/ directory, no need to manually configure each template anymore!

However, there is no `src/templates` folder. If I create one with a *.html file inside, let’s say `/src/template/my-template.html` and run the build, nothing seems to happen or change from the default setup.

How can I access my (compiled) templates via the dev server? My naïve approach would be to just call _http://localhost:8000/my-template.html_.

It would be great, if you described the templates feature in a little more detail.

**Comment by pnikolov** [comment]
@intellent 

Thanks for pointing this out - after [Release v5.4.0](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v5.4.0) the template files location is changed from `src/templates` to `src/` to keep assets files paths synced between `src` and `dist` paths for better development UX.

Sadly, the README was not updated to reflect this change. So, just place your templates files in the `src/` directory and they will be built. You can use the `index.html` template as example.

I have updated the README with the correct templates path.
