### ISSUE TITLE
Vulnerabilities found after npm ci

### ISSUE THREAD

**Issue by kyds3k** [WeAreAthlon/frontend-webpack-boilerplate#34]
With a new project, after running `npm ci`, I get:

`28 vulnerabilities (2 low, 3 moderate, 23 high)`

Should I ignore this or what is the recommended action?

**Comment by pnikolov** [comment]
@kyds3k 

The package dependencies can be reported for vulnerabilities every day, so you can try fixing those with the `npm` built-in provided tool [`npm-audit`](https://docs.npmjs.com/cli/v7/commands/npm-audit) by using the the following command:

**Scan your project for vulnerabilities and just show the details, without fixing anything:**
```sh
npm audit
```

**Scan your project for vulnerabilities and automatically install any compatible updates to vulnerable dependencies:**
```sh
npm audit fix
```

Have `audit fix` install _SemVer_-major updates to toplevel dependencies, not just _SemVer_-compatible ones:
```sh
npm audit fix --force
```
