### ISSUE TITLE
Fonts fail to load

### ISSUE THREAD

**Issue by vitali-sigel** [WeAreAthlon/frontend-webpack-boilerplate#39]
👋 Hi and thank you for the great Boilerplate!

The boilerplate fails to load any fonts in the demo and on my local machine.
In the console it says: 
![image](https://user-images.githubusercontent.com/39295117/133926807-eb4e69e6-a89a-495b-a580-82fb9e7fff0c.png)
I have tried different fonts to make sure the font is not broken.

Thank you & Greetings

**Comment by pnikolov** [comment]
@vitali-sigel 

Thanks for reporting this, this seems to be caused by the `url-loader` configuration. I am preperaing a new release that uses the built-in `webpack 5` assets management features that will fix this issue.

**Comment by pnikolov** [comment]
The newly released [Release v5.10.0](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v5.10.0) fixes the loading of fonts. The [demo page](https://weareathlon.github.io/frontend-webpack-boilerplate/) is updated to verify the fonts loading.

**Comment by vitali-sigel** [comment]
Thank you for fixing this so fast. It works perfectly 👍🙏
