### ISSUE TITLE
Cannot include partials in ejs files

### ISSUE THREAD

**Issue by isaacalves** [WeAreAthlon/frontend-webpack-boilerplate#49]
**Describe the bug**

Cannot include partials in .ejs files as it returns:

>  Error: Child compilation failed

If I use the `include('./nav.ejs')` syntax, I get:

> Template execution failed: ReferenceError: include is not defined

**To Reproduce**

1. Create a partial file, for example: `nav.ejs` in the root (same folder as `index.ejs`)
2. In `index.ejs`, add an include tag referencing the partial, for example `<%- include nav.ejs %>`
3. Run yarn dev

**Expected behavior**

It should render the `nav` partial in the `index.ejs` when compiling

**Comment by isaacalves** [comment]
This was solved by adding `ejs-webpack-loader` and updating the HTMLWebpackPlugin template option like this:

```
 template: `ejs-webpack-loader!${path.resolve(
    environment.paths.source,
    template.input
)}`,
```

**Comment by pnikolov** [comment]
@isaacalves thanks for sharing a possible solution! Would you mind submitting a PR so this feature can become part of the main release?
