### ISSUE TITLE
Working with PHP

### ISSUE THREAD

**Issue by dangelion** [WeAreAthlon/frontend-webpack-boilerplate#9]
Hi
I'm developing a project with simple PHP, that is a .php file for each page (ie. `index.php`, `about.php`) that include partials (ie. `header.php`, `footer.php` grouped in a folder `partials`)

Is it possibile to do this with your boilerplate and in case what's your advices?

I'm thinking the best way was: put php files (along with the folder `partials`) inside `src` folder, then the boilerplate should copy them into `dist` folder. This is just an idea, it could make no sense.

What do you think about?
Thanks

**Comment by pnikolov** [comment]
Hello,
This is a front-end boilerplate, so it does not have any features related to `php` files. But as it is a general boilerplate it can be referenced used by any server side applications.

 In you case you can make your php files include directly the `dist/*` files but you should disable the `HtmlWebpackPlugin` by remove it from the package and webpack configuration. Then you should use the `webpack` just to build your JS and CSS files without the HTML files.

You can also explore the [webpack-php-loader](https://www.npmjs.com/package/webpack-php-loader) and share some feedback, it should do it in your case.

**Comment by dangelion** [comment]
Hi @pnikolov 
thanks for answer. Some time ago you said: 

> The main purpose of this template is to be embedded in existing project setups for example WordPress, Laravel, Express applications etc

So I'm asking how do you use this with WP or Laravel since they're PHP based platforms?
Thanks

**Comment by pnikolov** [comment]
Hi @dangelion ,

Yes you are correct. Here is a simple example for *WordPress*. When you build a *WordPress* theme, you can put this boilerplate in a sub-directory called `/assets` under your theme directory and then you can register the output `dist` directory containing the built CSS / JS files directly in your `functions.php` file or any other included file:

```php
add_action( 'init', 'wordpress_custom_theme_load_assets' );

function wordpress_custom_theme_load_assets() {
  if ( ! is_admin() ) {
    $assets_url = get_bloginfo( 'template_url' ) . '/assets/dist';
    
    /**
     * Register Styles.
     * Example use: wp_register_style( $handle, $src, $deps, $ver, $media );
     */
    wp_register_style( 'app', $assets_url . '/css/app.css' );

    /**
     * Register Scripts.
     * Example use: wp_register_script( $handle, $src, $deps, $ver, $in_footer );
     */
    wp_register_script( 'app', $assets_url . '/js/app.js', false, true );
  }
}
```

By doing so you can get the advantages of `webpack` in terms of using `SASS` and `Babel` to transpile your JS(*ES6/7*) to your browser support matrix.

As I've mentioned in this case you cannot build your HTML files with `webpack` as you are dealing with PHP and server side technologies. `WordPress` will build your HTML files but `webpack` can build your CSS / JS.

*P.S. `webpack` will deal with the CSS references images, but for the images included directly in the HTML you need to reference them directly from the `src` directory or from your `WordPress` uploads.*

**Comment by dangelion** [comment]
Hi @pnikolov 
I'm still struggling to use your awesome boilerplate with simple php. So, following your previous advice, I disabled HtmlWebpackPlugin and putting an index.php in the dist folder it says "Cannot GET /". Also dist is gitignored so we lost the php files over the team. I still think a better way could be put .php files in the project root and copy automatically copy them in the dist but again I'll get the above error. I saw there's a CopyWebpackPlugin, it should be used for copy php files?
Let me know your thoughts

**Comment by pnikolov** [comment]
Hei @dangelion,

Can you share your setup (_sample file structure of your project_), so I can review and recommend a possible approach as before when I gave example with _WordPress_ configuration a few comments above.

**Comment by dangelion** [comment]
Hi @pnikolov 
here is my project structure. As you see it's just your boilerplate with added index.php and partials templates included in the index.php. 

![s](https://user-images.githubusercontent.com/4182418/85696735-7bd5f780-b6d9-11ea-8833-4a7e8b8c1bda.jpg)

**Comment by pnikolov** [comment]
So, as I've mentioned earlier this boilerplate is for the front-end side of your code, it has no impact how you structure your back-end code(_in your case PHP_).

A good practice is to separate the PHP files from the front-end assets source files.
 
For example:

```
/project
    + assets // this is the directory to host the boilerplate
        + node_modules/
        + src/
        - package.json
        - webpack.config.js
        - ...
    + partials/
    + public
        + assets/
            + dist/
                + js/
                + css/
                + fonts/
                + images/
        - index.php
        - ...
```

Working with PHP files means that you **cannot** use `webpack` to load your CSS/JS files in the rendered HTML files within the PHP scripts. What you need to do is to **manually link** the built CSS/JS files from the `/dist` directory. 
For example, in this case you can crate your domain document root to point to the `/public` server directory to prevent web access to other server resources.

```HTML
// index.php

<head>
  <link rel="stylesheet" href="/assets/dist/css/app.css">
</head>
<body>
  <script type="text/javascript" src="/assets/dist/js/app.js"></script>
</body>
```

This also require to reconfigure the `webpack.config.js` configuration to relocate your `dist` directory to not be in the same level as your `src` file..

**Comment by sixtyniner-official** [comment]
Regarding templating,have you thought about template engine implementation, [twig.js](https://github.com/twigjs/twig.js/), [nunjacks](https://mozilla.github.io/nunjucks/) or [mustache](https://mustache.github.io/)?

**Comment by pnikolov** [comment]
Hey @sixtyniner-official ,

Can you explain more or give an example regarding the need to use template engine with `webpack` managed assets?

**Comment by sixtyniner-official** [comment]
Template engine is nice way to organize (HTML) code in smaller, functional components using one of popular engines, [here](https://github.com/tomaszbujnowicz/frontie-webpack) you can check how it's done using twigjs

**Comment by pnikolov** [comment]
@sixtyniner-official 

This boilerplate tries to be as generic as possible. With additional packages and configuration on top you can use it with any template engine.

**Comment by dangelion** [comment]
Hi @pnikolov 
I installed the new release. This is my project tree:

![Schermata 2021-04-26 alle 10 22 23](https://user-images.githubusercontent.com/4182418/116051881-6030da00-a679-11eb-9db3-e990ac27bf35.jpg)

But in this way I can't use the hot reload feature because launching `npm run dev` it opens http://localhost:8000/ with root on a subfolder, not in the project root where is the index.php.
Any advices?
